### PR TITLE
Fix Polymer remove notification

### PR DESCRIPTION
**Pull request by alshakero**
Fixes: https://github.com/Palindrom/palindrom-polymer-client/issues/47

should I PR to `level1` with a patch version after merging this?

### CODE REVIEW

**Comment by warpech** [comment]
Can we have a test for this fix?

**Comment by alshakero** [comment]
The weird thing is that we do have a test for the thing. And it is passing.
https://github.com/Palindrom/palindrom-polymer-client/blob/eb4ac9de322bd89415f2dd49c50dcbd3eb55bc3f/test/d-b-n_smoke/simple.html#L59-L66

**Comment by warpech** [comment]
Any progress with this?

**Comment by alshakero** [comment]
@warpech is this urgent? I'm totally invested in Polymer but thought I should ask before delaying it further.

**Comment by warpech** [comment]
Yes, this is urgent because it affects Starcounter 2.3.1.x and should be fixed and tested before release.

**Comment by alshakero** [comment]
I tried every scenario to reproduce this (keeping the view after `op: delete`) and couldn't manage with and without the fix. My theory is that it's either a `starcounter-include` or an `imported-template` issue. One of them can be treating `undefined` and `null` differently when they receive the forwarded notification.

**Comment by warpech** [comment]
This issue is totally reproducible with the instructions posted in https://github.com/Starcounter/Home/issues/250#issuecomment-335796192. Have you tried that?

**Comment by alshakero** [comment]
Not really, then I'll need access to WebsiteEditor.

**Comment by warpech** [comment]
"Website" is just a repo that has two apps "WebsiteEditor" and "WebsiteProvider". But now you know that :)

**Comment by alshakero** [comment]
@warpech done. To verify remove this line:
```js
templateDomBind.notifyPath(polymerPath, null, false);
```
and see the test failing.

**Comment by alshakero** [comment]
Any update on this? It would be cool to PR to level1 `sc-include` and this.

**Pull request merged**
