### PR TITLE
Bump version

### PR DESCRIPTION
**Pull request by alshakero**

### CODE REVIEW

**Comment by alshakero** [comment]
Apparently @alemoi created the same patch for v2.3 and v2.4, see the commit here https://github.com/Starcounter/level1/commit/56045c414178b3efe3c19ea8f853947012857a50

Should we ask him to drop the v2.3 branch one? And merge the other?

**Comment by alemoi** [comment]
> Should we ask him to drop the v2.3 branch one? And merge the other?

You decide, guys :)

**Comment by warpech** [comment]
I am confused by https://github.com/Starcounter/Home/issues/340 being included in Starcoutner 2.3.x, because it was tracked in the `Odessa` project board only.

I believe that it is fine to include that in 2.3.2, but that is a change of plans that should be agreed with @miyconst.

**Comment by alshakero** [comment]
I think I already know @miyconst opionion. He would say to merge it to both since [he agreed to drop `puppet` support from 2.3.2](https://github.com/Starcounter/level1/issues/4441#issuecomment-359526308). I think that's a bigger changes and he approved of it.

**Comment by alshakero** [comment]
I prepared two PRs for SCF 1.x and 2.x.

**Pull request merged**
