### PR TITLE
Attributes improvements

### PR DESCRIPTION
**Pull request by warpech**
new features:

- default value for remoteUrl was requested here: Palindrom/Palindrom#247
- boolean attribute conversion is needed for fixing the Polymer demo page in the docs: http://localhost:5000/lab/polymer/index.html. This also fixes the issue #3

Both changes have tests

### CODE REVIEW

**Comment by miyconst** [comment]
Should there instead be an attribute `use-http` without value set?

**Comment by tomalec** [comment]
> Should there instead be an attribute use-http without value set?

I agree. It makes it closer to native convention. Where `hasAttribute` matters for booleans . On the other hand it make it less consistent with Palindrom props, and their `true` defaults. 

Maybe then we could make it so only `"false"` is falsy, then at least `attr, attr="", attr="foo", attr="true"` are truthy as for native ones.

**Comment by warpech** [comment]
How about we track this idea in a new issue? This PR tries to fix something that just works wrong at this moment, which I think is a step in good direction with minimum effort.

**Review by miyconst — APPROVED** [review]

**Comment by tomalec** [comment]
Issue created at https://github.com/Palindrom/palindrom-client/issues/85

**Pull request merged**
